server:
  port: 8090

spring:
  security:
    user:
      name: admin
      password: 123456
  datasource:
    username: root
    password: Shiqi0828.
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://8.142.94.150:3306/dev
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://8.142.94.150:3306/dev
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      max-lifetime: 540000
      minimum-idle: 5
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:/db/master.xml

logging:
  config: classpath:log4j2-spring-dev.xml


springdoc:
  swagger:
    title: 用户中心
    description: 用户中心
    version: 1.0.0
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /miracle
    persistAuthorization: true



jwt:
  expireTime: 180
  tokenSecret: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJ6l



